apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jy-companion

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - apisix-deployment.yaml
  - apisix-service.yaml

commonLabels:
  app.kubernetes.io/part-of: jy-companion
  app.kubernetes.io/managed-by: kustomize
